# Generated by Django 3.0.8 on 2020-07-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_plate', models.CharField(max_length=10)),
                ('plate_pic', models.ImageField(upload_to='')),
                ('cover_pic', models.ImageField(upload_to='')),
                ('checked', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScannedLogbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StarObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_object', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('ra', models.CharField(max_length=20)),
                ('dec', models.FloatField()),
                ('dec_obs', models.FloatField()),
                ('ha', models.CharField(max_length=20)),
                ('t_start', models.TimeField()),
                ('t_end', models.TimeField()),
                ('exposure', models.CharField(max_length=20)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('focus', models.CharField(max_length=20)),
                ('staand_plaat', models.FloatField(blank=True, null=True)),
                ('emulsion', models.CharField(blank=True, max_length=20, null=True)),
                ('emulsion_no', models.CharField(blank=True, max_length=20, null=True)),
                ('film', models.CharField(max_length=20)),
                ('plate_size', models.CharField(max_length=20)),
                ('camera_filter', models.CharField(max_length=20, verbose_name='Filter')),
                ('grating', models.CharField(blank=True, max_length=20, null=True)),
                ('transparency', models.CharField(blank=True, max_length=20, null=True)),
                ('seeing', models.CharField(blank=True, max_length=20, null=True)),
                ('observer', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
