# Generated by Django 3.0.8 on 2020-07-11 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plate_archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='starobject',
            name='plate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='star_object', to='plate_archive.Plate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='starobject',
            name='date',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='exposure',
            field=models.CharField(max_length=20, verbose_name='Exposure (seconds)'),
        ),
    ]
