# Generated by Django 3.0.8 on 2020-07-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_archive', '0006_plate_preview_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starobject',
            name='dec',
            field=models.FloatField(verbose_name='Declination (degree)'),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='dec_obs',
            field=models.FloatField(verbose_name='Observed declination (degree)'),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='focus',
            field=models.CharField(max_length=20, verbose_name='Focus (mm)'),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='ha',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='plate_size',
            field=models.CharField(max_length=20, verbose_name='Plate size (mm x mm)'),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='staand_plaat',
            field=models.FloatField(blank=True, null=True, verbose_name='Plate Stand (degree)'),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature (Celcius)'),
        ),
    ]
