# Generated by Django 3.0.8 on 2020-07-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_archive', '0008_auto_20200715_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starobject',
            name='camera_filter',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Filter'),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='focus',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Focus (mm)'),
        ),
    ]
