# Generated by Django 3.0.8 on 2020-07-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_archive', '0010_auto_20200715_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starobject',
            name='star_object',
            field=models.CharField(max_length=20),
        ),
    ]
