# Generated by Django 3.0.8 on 2020-07-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_archive', '0011_auto_20200715_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starobject',
            name='exposure',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Exposure (seconds)'),
        ),
    ]
