# Generated by Django 3.0.8 on 2020-07-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_archive', '0012_auto_20200718_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starobject',
            name='dec',
            field=models.FloatField(blank=True, null=True, verbose_name='Declination (degree)'),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='dec_obs',
            field=models.FloatField(blank=True, null=True, verbose_name='Observed declination (degree)'),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='ra',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
