# Generated by Django 3.0.8 on 2020-07-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_archive', '0013_auto_20200718_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starobject',
            name='t_end',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='starobject',
            name='t_start',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
