# Generated by Django 3.0.8 on 2020-08-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_archive', '0015_plate_logbook_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='cover_pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='plate',
            name='logbook_pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='plate',
            name='plate_pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='plate',
            name='preview_pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
