# Generated by Django 3.0.8 on 2020-08-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_archive', '0017_auto_20200814_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cover',
            name='cover_id',
        ),
        migrations.RemoveField(
            model_name='cover',
            name='cover_note',
        ),
        migrations.RemoveField(
            model_name='cover',
            name='envelope',
        ),
        migrations.RemoveField(
            model_name='cover',
            name='meas_auth',
        ),
        migrations.RemoveField(
            model_name='cover',
            name='meas_date',
        ),
        migrations.AddField(
            model_name='plate',
            name='cover_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='cover_note',
            field=models.TextField(blank=True, null=True, verbose_name='Cover remarks'),
        ),
        migrations.AddField(
            model_name='plate',
            name='meas_auth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Measurement officer'),
        ),
        migrations.AddField(
            model_name='plate',
            name='meas_date',
            field=models.CharField(blank=True, default='1970-01-01', max_length=10, null=True, verbose_name='Measurement date'),
        ),
    ]
