# Generated by Django 3.0.8 on 2020-08-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_archive', '0018_auto_20200814_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='cover_date',
            field=models.CharField(blank=True, default='1970-01-01', max_length=10, null=True, verbose_name='Cover date'),
        ),
        migrations.AddField(
            model_name='plate',
            name='cover_dec',
            field=models.FloatField(blank=True, null=True, verbose_name='Cover dec (degree)'),
        ),
        migrations.AddField(
            model_name='plate',
            name='cover_emul',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cover emulsion'),
        ),
        migrations.AddField(
            model_name='plate',
            name='cover_exp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cover exposure (seconds)'),
        ),
        migrations.AddField(
            model_name='plate',
            name='cover_filter',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cover filter'),
        ),
        migrations.AddField(
            model_name='plate',
            name='cover_grat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cover grating'),
        ),
        migrations.AddField(
            model_name='plate',
            name='cover_object',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cover Object'),
        ),
        migrations.AddField(
            model_name='plate',
            name='cover_obs',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cover observer'),
        ),
        migrations.AddField(
            model_name='plate',
            name='cover_prog',
            field=models.CharField(blank=True, default='Double Star', max_length=20, null=True, verbose_name='Cover program'),
        ),
        migrations.AddField(
            model_name='plate',
            name='cover_ra',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cover RA (hh mm)'),
        ),
        migrations.AddField(
            model_name='plate',
            name='cover_t_end',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cover T_end'),
        ),
        migrations.AddField(
            model_name='plate',
            name='cover_t_start',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cover T_start'),
        ),
        migrations.AddField(
            model_name='plate',
            name='plate_qual',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Plate Quality'),
        ),
    ]
