# Generated by Django 3.0.8 on 2020-08-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_archive', '0019_auto_20200814_2336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cover',
        ),
        migrations.AlterField(
            model_name='plate',
            name='cover_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cover date'),
        ),
    ]
