# Generated by Django 3.0.8 on 2020-08-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_archive', '0020_auto_20200818_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Unavailable', 'Unavailable'), ('Available', 'Available'), ('Processed', 'Processed')], max_length=100, null=True)),
            ],
        ),
    ]
