# Generated by Django 3.0.8 on 2020-08-23 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plate_archive', '0021_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='plate_archive.Plate'),
        ),
    ]
