# Generated by Django 3.0.8 on 2020-08-23 03:29

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plate_archive', '0023_auto_20200823_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='date_modified',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor=model_utils.fields.StatusField(blank=True, choices=[('Unavailable', 'Unavailable'), ('Available', 'Available'), ('Processed', 'Processed')], default='Unavailable', max_length=100, no_check_for_status=True, null=True), null=True, when={'Processed'}),
        ),
        migrations.AlterField(
            model_name='plate',
            name='status',
            field=model_utils.fields.StatusField(blank=True, choices=[(0, 'dummy')], default='Unavailable', max_length=100, no_check_for_status=True, null=True),
        ),
    ]
