# Generated by Django 3.0.8 on 2020-08-23 03:44

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plate_archive', '0024_auto_20200823_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='date_modified',
        ),
        migrations.AlterField(
            model_name='plate',
            name='status',
            field=model_utils.fields.StatusField(blank=True, choices=[(0, 'dummy')], default='unavailable', max_length=100, no_check_for_status=True, null=True),
        ),
    ]
