# Generated by Django 3.0.8 on 2020-08-23 04:18

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plate_archive', '0025_auto_20200823_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='date_modified',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor=model_utils.fields.StatusField(choices=[('unavailable', 'Unavailable'), ('available', 'Available'), ('processed', 'Processed')], default='unavailable', max_length=100, no_check_for_status=True), when={'Processed'}),
        ),
        migrations.AlterField(
            model_name='plate',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='unavailable', max_length=100, no_check_for_status=True),
        ),
    ]
