# Generated by Django 3.0.8 on 2020-08-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plate_archive', '0030_auto_20200823_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plate',
            options={'ordering': ('status',)},
        ),
    ]
