# Generated by Django 3.0.8 on 2020-08-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_archive', '0031_auto_20200823_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='plate',
            name='plate_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='plate',
            name='preview_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
